<?php

use Fisharebest\Webtrees\I18N;
use JustCarmen\Webtrees\Internationalization\MoreI18N;

/**
 * @var int $generation
 * @var int $limit
 */

?>

<div id="<?= $generation ?>" class="jc-generation-block-header d-flex justify-content-between align-items-center border-bottom border-primary mb-3">
    <span class="fs-4"><?= MoreI18N::xlate('Generation') . ' ' . $generation ?></span>
    <?php if ($generation % ($limit * max(1, $page - 1)) <> 1) : ?>
        <a href="#top" class="d-print-none"><?= MoreI18N::xlate('back to top') ?></a>
    <?php endif ?>
</div>
