<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

?>

<div class="jc-generation-block-header d-flex justify-content-between align-items-center border-bottom border-primary mb-3">
    <span class="fs-4"><?= I18N::translate('Generation') . ' ' . $generation ?></span>
    <?php if ($generation > 1) : ?>
    <a href="#top"><?= I18N::translate('back to top') ?></a>
    <?php endif ?>
</div>
