<?php

use Fisharebest\Webtrees\I18N;

?>

<?php if ($module->checkPrivacy($pids, true)) : ?>
    <div class="jc-generation-block-content jc-private">
        <?= I18N::translate('The details of this generation are private.') ?>
    </div>
<?php else : ?>
    <ol class="jc-generation-block-content list-unstyled">
        <?php foreach (array_unique($pids) as $pid) : ?>
            <?php $person = $module->getPerson($pid) ?>
            <?php if (!$module->hasParentsInSameGeneration($person)) : ?>
                <?php
                $family = $module->getFamily($person);
                if (!empty($family)) {
                    $pid = $family->xref();
                }
                $class = $person->canShow() ? 'jc-family-block' : 'jc-family-block jc-private';
                ?>

                <span id="<?= $pid ?>" name="<?= $pid ?>"></span>
                <li class="<?= $class ?> ps-5 mb-3"><?= $module->printIndividual($person) ?></li>
            <?php endif ?>
        <?php endforeach ?>
    </ol>
<?php endif ?>
