<?php

use Fisharebest\Webtrees\I18N;

?>

<p>
    <?= I18N::translate('You have not created a link yet.') ?>
</p>
<p>
    <?= I18N::translate('Go to the page of any individual and open the edit menu to create a new link to the Fancy Treeview Page.') ?>
</p>
    <?= I18N::translate('You can also create links from the Fancy Treeview page itself.') ?>
</p>
<p>
    <?= I18N::translate('The links created will be shown in this block.') ?>
</p>

