<?php

use Fisharebest\Webtrees\I18N;

?>

<?php if ($module->checkPrivacy($pids, true)) : ?>
    <div class="jc-generation-block-content jc-private">
        <?= I18N::translate('The details of this generation are private.') ?>
    </div>
<?php else : ?>
    <ol class="jc-generation-block-content list-unstyled">
        <?php if ($module->type === 'ancestors' && $module->generation > 1): ?>
            <div class="mb-3 small fst-italic">
                <?= count($pids) . ' ' . I18N::translate('of') . ' ' .
                    I18N::number(pow(2, $module->generation - 1)) . ' ' . strtolower(I18N::translate('Individuals')) .
                    ' (' . I18N::percentage(count($pids) / pow(2, $module->generation - 1), 2) . ' ' . I18N::translate('complete') . ').'
                ?>
            </div>
        <?php endif ?>
        <?php foreach (array_unique($pids) as $pid) : ?>
            <?php $person = $module->getPerson($pid) ?>
            <?php if (!$module->hasParentsInSameGeneration($person)) : ?>
                <?php
                $family = $module->getFamily($person);
                if (!empty($family)) {
                    $pid = $family->xref();
                }
                $class = $person->canShow() ? 'jc-family-block' : 'jc-family-block jc-private';
                ?>

                <span id="<?= $pid ?>" name="<?= $pid ?>"></span>
                <li class="<?= $class ?> ps-5 mb-3"><?= $module->printIndividual($person) ?></li>
            <?php endif ?>
        <?php endforeach ?>
    </ol>
<?php endif ?>
