<?php

use Fisharebest\Webtrees\I18N;

?>

<div id="<?= $generation ?>" class="jc-generation-block-header d-flex justify-content-between align-items-center border-bottom border-primary mb-3">
    <span class="fs-4"><?= I18N::translate('Generation') . ' ' . $generation ?></span>
    <?php if ($generation % ($limit * max(1, $page - 1)) <> 1) : ?>
        <a href="#top" class="d-print-none"><?= I18N::translate('back to top') ?></a>
    <?php endif ?>
</div>
