<?php
use Fisharebest\Webtrees\Registry;
?>

<ul class="block generation-block">
    <?php foreach ($individuals as $individual): ?>
    <li class="family">
        <?= $individual->fullName() ?>
            <?php foreach ($individual->spouseFamilies() as $family): ?>
                <?= $family->spouse($individual)->fullName() ?>
            <?php endforeach ?>
        <?php endforeach ?>
    </li>
</ul>
