<?php

use Fisharebest\Webtrees\I18N;

?>

<p>
    <?= I18N::translate('Click here to create or remove a link to the Fancy Treeview page.') ?>
</p>
<p>
    <?= I18N::translate('The links created will be included in the Fancy Treeview menu and in the Fancy Treeview homepage block.') ?>
    <?= I18N::translate('The title of the menu and homepage block is \'Family Tree Overview\'.') ?>
</p>
<p>
    <?= I18N::translate('You can use both the menu and homepage block or choose to use either.') ?>
</p>
<p>
    <?= I18N::translate('Go to the control panel to set the menu access level. There you can also choose to hide the menu.') ?>
</p>
<p>
    <?= I18N::translate('Go to the homepage, click on my pages/customize this page to add the Fancy Treeview homepage block with the created links.') ?>
</p>
<p>
    <?= I18N::translate('The menu and homepage block contain the same links. However, the appearance of the homepage block has been made more attractive by adding images for the links.') ?>
</p>
<p>
    <?= I18N::translate('You can create links from the Fancy Treeview page or from the edit menu on the individual page.') ?>
</p>

