<?php

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
?>

<?php if (Auth::isAdmin()) : ?>
    <div class="jc-fancy-treeview-menu-edit collapse">
        <div class="dropdown-divider"></div>
        <span class="dropdown-item-text fw-bold"><?= I18N::translate('Link to Fancy Treeview page') ?>
            <a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route('module', ['module' => $module->name(), 'action' => 'HelpText'])) ?>">
                <?= view('icons/help') ?>
            </a>
        </span>
        <?php if ($module->isMenuItem($tree, $individual->xref(), 'ancestors')) : ?>
            <?= View($module->name() . '::menu-item-remove', ['tree' => $tree, 'xref' => $individual->xref(), 'type' => 'ancestors', 'url' => $individual->url(), 'text' => I18N::translate('Remove link to ancestors page')]); ?>
        <?php else : ?>
            <?= View($module->name() . '::menu-item-add', ['tree' => $tree, 'xref' => $individual->xref(), 'type' => 'ancestors', 'url' => $individual->url(), 'text' => I18N::translate('Create link to ancestors page')]); ?>
        <?php endif ?>
        <?php if ($module->isMenuItem($tree, $individual->xref(), 'descendants')) : ?>
            <?= View($module->name() . '::menu-item-remove', ['tree' => $tree, 'xref' => $individual->xref(), 'type' => 'descendants', 'url' => $individual->url(), 'text' => I18N::translate('Remove link to descendants page')]); ?>
        <?php else : ?>
            <?= View($module->name() . '::menu-item-add', ['tree' => $tree, 'xref' => $individual->xref(), 'type' => 'descendants', 'url' => $individual->url(), 'text' => I18N::translate('Create link to descendants page')]); ?>
        <?php endif ?>
    </div>

    <?php View::push('javascript') ?>
    <script>
        $('.wt-page-menu-items .dropdown-item:last-child').after($('.jc-fancy-treeview-menu-edit').addClass('show'));
    </script>
    <?php View::endpush() ?>

<?php endif ?>
