<?php

use Fisharebest\Webtrees\I18N;

?>

<div id="jc-fancy-treeview-page" class="jc-fancy-treeview-page col-lg-9 mx-auto">
    <span id="top" name="top"></span>
    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-primary" href="<?= e($button_url) ?>"><?= $button_text ?></a>
    </div>
    <h2 class="wt-page-title"><?= $page_title ?></h2>
    <ol class="jc-fancy-treeview-page-body list-unstyled"><?= $page_body ?></ol>
</div>
