<?php

use Fisharebest\Webtrees\I18N;

?>

<nav aria-label="jc-page-navigation">
    <ul class="pagination justify-content-center pt-3">
        <li class="page-item<?= $current_page === 1 ? ' disabled' : ''?>">
            <a class="page-link" href="<?= $module->getUrl($tree, $pid, '', $current_page - 1) ?>" tabindex="-1" aria-disabled="<?= $current_page === 1 ? 'true' : 'false'?>">
                <?= I18N::translate('previous') ?>
            </a>
        </li>
        <?php for ($page = 1; $page <= $total_pages; $page++): ?>
        <li <?= $page === $current_page ? 'class="page-item active" aria-current="page"' : 'class="page-item"'?>>
            <a class="page-link" href="<?= $module->getUrl($tree, $pid, '', $page) ?>"><?= $page ?></a>
        </li>
        <?php endfor ?>
        <li class="page-item<?= $current_page === $total_pages ? ' disabled' : ''?>">
            <a class="page-link" href="<?= $module->getUrl($tree, $pid, '', $current_page + 1) ?>" tabindex="-1" aria-disabled="<?= $current_page === $total_pages ? 'true' : 'false'?>">
                <?= I18N::translate('next') ?>
            </a>
        </li>
    </ul>
</nav>
