<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<div class="jc-fancy-treeview mb-5">
    <form method="post">
        <?= csrf_field() ?>
        <input type="hidden" name="save" id="save" value="1">
         <!-- PAGE LIMIT -->
         <div class="row mb-3">
            <label class="col-form-label col-sm-3">
                <?= I18N::translate('Maximum number of generations per page') ?>
            </label>
            <div class="col-sm-1">
                <?= view('components/select', ['name' => 'page-limit', 'selected' => $page_limit, 'options' => [1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5]]) ?>
            </div>
            <div class="form-text col-sm-9 offset-sm-3">
                <?= /* I18N: Help text for the “Maximum number of generations per page” configuration setting */
                    I18N::translate('Select the maximum number of generations to show on the Fancy Treeview page.');
                ?>
                <?= I18N::translate('More generations require more memory and it takes longer for the page to fully load.'); ?>
            </div>

        </div>
        <!-- TAB LIMIT -->
        <div class="row mb-3">
            <label class="col-form-label col-sm-3">
                <?= I18N::translate('Maximum number of generations per tab') ?>
            </label>
            <div class="col-sm-1">
                <?= view('components/select', ['name' => 'tab-limit', 'selected' => $tab_limit, 'options' => [1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5]]) ?>
            </div>
            <div class="form-text col-sm-9 offset-sm-3">
                <?= /* I18N: Help text for the “Maximum number of generations per page” configuration setting */
                    I18N::translate('Select the maximum number of generations to show on the individual page tab.');
                ?>
                <?= I18N::translate('More generations require more memory and it takes longer for the page to fully load.'); ?>
            </div>
        </div>
        <!-- SHOW SINGLES -->
        <fieldset class="form-group mb-3">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Show singles') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'show-singles', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$show_singles]) ?>
                    <div class="form-text">
					    <?= /* I18N: Help text for the “Show singles” configuration setting */
                            I18N::translate('Turn this option on if you want to display singles in the next generation.' .
                            ' Singles are individuals without partner and children. With this option turned on, each child of a family will be displayed' .
                            ' in a detailed manner in the next generation. This setting only affects the page or tab containing the descendants.')
                        ?>
                    </div>
                </div>
            </div>
        </fieldset>
         <!-- CHECK RELATIONSHIP BETWEEN PARTNERS -->
         <fieldset class="form-group mb-3">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Check relationship between partners') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'check-relationship', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$check_relationship]) ?>
                    <div class="form-text">
					    <?= /* I18N: Help text for the “Check relationship between partners” configuration setting */
                            I18N::translate('With this option turned on, the script checks if a (married) couple has the same ancestors.' .
                            ' If a relationship between the partners is found, a text will appear between brackets after the spouses’ name to indicate the blood relationship.')
                        ?>
                    </div>
                    <div class="form-text">
						<?= /* I18N: Warning when using the “Check relationship between partners” configuration setting */
                            I18N::translate('<strong>Note</strong>: this option can be time and/or memory consuming, especially on large trees.' .
                            ' It can cause very slow page loading or an ’execution time out error’ on your server. If you notice such a behavior,' .
                            ' reduce the maximum number of generations per page or tab and/or don’t use it in combination with the option ’show singles’.' .
                            ' If you still have problems, leave the answer at ’no’.')
                        ?>
                    </div>
                </div>
            </div>
        </fieldset>
         <!-- THUMBNAIL SIZE -->
         <div class="row mb-3">
            <label class="col-form-label col-sm-3">
                <?= I18N::translate('Thumbnail size') ?>
            </label>
            <div class="col-auto">
                <input class="form-control" type="text" name="thumb-size" size="3" value="<?= $thumb_size ?>" required>
            </div>
            <div class="col-auto align-self-center">px</div>
        </div>
        <!-- CROP THUMBNAILS TO SQUARE -->
        <fieldset class="form-group mb-3">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Crop thumbnails to square') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'crop-thumbs', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$crop_thumbs]) ?>
                </div>
            </div>
        </fieldset>
         <!-- MEDIA TYPE PHOTO -->
         <fieldset class="form-group mb-3">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Show only media from the type \'photo\'') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'media-type-photo', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$media_type_photo]) ?>
                    <div class="form-text">
					    <?= /* I18N: Help text for the “Show only media from the type 'photo'” configuration setting */
                            I18N::translate('Turn this option on if you want to display images from the type photo only.' .
                            ' Other highlighted images like certificates, documents or tombstones will not be used.' .
                            ' If you did not differentiate by media type in your gedcom leave the answer at ’no’.')
                        ?>
                    </div>
                </div>
            </div>
        </fieldset>
        <!-- SAVE BUTTON -->
        <hr/>
        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= I18N::translate('save') ?>
        </button>
    </form>
</div>

