<?php

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<div class="jc-fancy-treeview mb-5">
    <!-- ADMIN PAGE CONTENT -->

    <!-- *** FORM 1 *** -->
    <form class="form-horizontal" method="post" name="form1" action="<?= e(route('module', ['module' => '_jc-fancy-treeview_', 'action' => 'Form1']) ?>">
        <?= csrf_field() ?>
        <input type="hidden" name="form1" id="form1" value="1">
        <input type="hidden" name="save1" id="save1" value="1">
        <input type="hidden" name="switch1" id="switch1" value="1">
        <!-- TREE LIST -->
        <div class="row mb-3">
            <label class="col-sm-3 col-form-label for=" tree"><?= I18N::translate('Family tree') ?></label>
            <div class="col-sm-9">
                <select class="form-control" id="tree" name="tree-id" type="text" required>
                    <option value=""><?= I18N::translate('&lt;select&gt;') ?></option>
                    <?php foreach ($all_trees as $tree) : ?>
                        <?php if($tree->id() === (int)$tree_id) : ?>
                        <option value="<?= $tree->id() ?>" selected="selected">
                            <?= $tree->title() ?>
                        </option>
                        <?php else : ?>
                        <option value="<?= $tree->id() ?>">
                            <?= $tree->title() ?>
                        </option>
                        <?php endif; ?>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </form>

    <!--ACCORDION -->
    <div class="accordion" id="accordionExample"">
        <!-- ACCORDION 1 -->
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    <?= I18N::translate('Pages') ?>
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <?php if (empty($FTV_SETTINGS) || (!empty($FTV_SETTINGS) && !$this->searchArray($FTV_SETTINGS, 'TREE', $this->tree()->getTreeId()))): ?>
                        <div class="alert alert-info alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="' . I18N::translate('close') . '">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <p class="small text-muted">
                                <?= /* I18N: Help text for creating Fancy Treeview pages */ I18N::translate('Use the search form below to search for a root person. After a successful search the Fancy Treeview page will be automatically created. You can add as many root persons as you want.') ?>
                            </p>
                        </div>
                    <?php endif; ?>
                    <!-- *** FORM 2 *** -->
                    <div id="ftv-search-form" class="form-group alert alert-info">
                        <form class="form-inline" method="post" name="form2">
                            <!-- SURNAME SEARCH FIELD -->
                            <div class="form-group">
                                <label class="control-label">
                                    <?= I18N::translate('Search root person') ?>
                                </label>
                                <input
                                    class="form-control"
                                    data-autocomplete-type="SURN"
                                    id="surname-search"
                                    name="SURNAME"
                                    placeholder="<?= I18N::translate('Surname') ?>"
                                    type="text"
                                    >
                                <label class="checkbox-inline">
                                    <?= view('components/checkbox-inline', ['label' => I18N::translate('Russell'), 'name' => 'soundex_std', 'checked' => $soundex_std]) ?>
                                </label>
                                <label class="checkbox-inline">
                                <?= view('components/checkbox-inline', ['label' => I18N::translate('Daitch-Mokotoff'), 'name' => 'soundex_dm', 'checked' => $soundex_dm]) ?>
                                </label>
                                <button name="search" class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                    <?= I18N::translate('search') ?>
                                </button>
                            </div>
                            <!-- PID SEARCH FIELD -->
                            <?php $class = I18N::direction() === 'rtl' ? 'pull-left' : 'pull-right'; ?>
                            <div class="form-group <?= $class ?>">
                                <label class="control-label" for="pid-search">
                                    <?= I18N::translate('Or enter an ID') ?>
                                </label>
                                <input
                                    class="form-control"
                                    data-autocomplete-type="INDI"
                                    id="pid-search"
                                    name="PID"
                                    placeholder="<?= I18N::translate('Search ID by name') ?>"
                                    type="text"
                                    value=""
                                    >
                                <button name="Ok" class="btn btn-primary" type="submit">
                                    <i class="fa fa-check"></i>
                                    <?= I18N::translate('ok') ?>
                                </button>
                            </div>
                        </form>
                        <!-- *** FORM 3 *** -->
                        <form class="form-horizontal" method="post" name="form3">
                            <!-- TABLE -->
                            <table id="search-result-table" class="table" style="display: none">
                                <thead>
                                    <tr>
                                        <th><?= I18N::translate('Root person') ?></th>
                                        <?php if (!$this->options('use_fullname')): ?>
                                            <th><?= I18N::translate('Surname in page title') ?></th>
                                        <?php endif; ?>
                                        <th><?= I18N::translate('Page title') ?></th>
                                        <th><?= I18N::translate('Access level') ?></th>
                                        <th><?= I18N::translate('Add') ?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <!-- ROOT PERSONS FULL NAME -->
                                        <td id="root">
                                            <?php if ($this->options('use_fullname')): ?>
                                                <input
                                                    name="surname"
                                                    type="hidden"
                                                    value=""
                                                    >
                                                <?php endif ?>
                                            <input
                                                name="pid"
                                                type="hidden"
                                                value=""
                                                >
                                            <input
                                                name="sort"
                                                type="hidden"
                                                value=""
                                                >
                                            <span></span>
                                        </td>
                                        <?php if (!$this->options('use_fullname')): ?>
                                            <!-- SURNAME IN PAGE TITLE -->
                                            <td id="surn">
                                                <label class="showname"></label>
                                                <input
                                                    class="form-control editname"
                                                    name="surname"
                                                    type="text"
                                                    value=""
                                                    >
                                            </td>
                                        <?php endif ?>
                                        <!-- PAGE TITLE -->
                                        <td id="title"></td>
                                        <!-- ACCESS LEVEL -->
                                        <td>
                                        <?= view('components/select', ['name' => 'access-level', 'selected' => $tree->getPreference('access-level'), 'options' => array_slice(Auth::accessLevelNames(), 0, 2, true)]) ?>
                                        </td>
                                        <!-- ADD BUTTON -->
                                        <td>
                                            <button	type="submit" name="add" class="btn btn-success btn-sm" title="<?php I18N::translate('Add'); ?>">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </form>
                    </div>
                    <?= $this->addMessage("error", "danger", true) ?>
                    <?= $this->addMessage('update-settings', 'success', true, I18N::translate('The settings for this tree are succesfully updated')) ?>
                    <div id="fancy-treeview-form" class="form-group">
                        <?php if (!empty($FTV_SETTINGS) && $this->searchArray($FTV_SETTINGS, 'TREE', $this->tree()->getTreeId())): ?>
                            <form class="form-horizontal" method="post" name="form4">
                                <!-- TABLE -->
                                <table id="fancy-treeview-table" class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th><?= I18N::translate('Root person') ?></th>
                                            <?php if (!$this->options('use_fullname')): ?>
                                                <th><?= I18N::translate('Surname in page title') ?></th>
                                            <?php endif; ?>
                                            <th><?= I18N::translate('Page title') ?></th>
                                            <th><?= I18N::translate('Access level') ?></th>
                                            <th><?= I18N::translate('Delete') ?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($FTV_SETTINGS as $key => $this_ITEM): ?>
                                            <?php if ($this_ITEM['TREE'] == $this->tree()->getTreeId()): ?>
                                                <?php if (Individual::getInstance($this_ITEM['PID'], $this->tree())): ?>
                                                    <tr class="sortme">
                                                        <!-- ROOT PERSONS FULL NAME -->
                                                        <td>
                                                            <input
                                                                name="pid[<?= $key ?>]"
                                                                type="hidden"
                                                                value="<?= $this_ITEM['PID'] ?>"
                                                                >
                                                            <input
                                                                name="sort[<?= $key ?>]"
                                                                type="hidden"
                                                                value="<?= $this_ITEM['SORT'] ?>"
                                                                >
                                                                <?= Individual::getInstance($this_ITEM['PID'], $this->tree())->getFullName() . '' ?>
                                                            (<?= Individual::getInstance($this_ITEM['PID'], $this->tree())->getLifeSpan() ?>)
                                                        </td>
                                                        <?php if (!$this->options('use_fullname')): ?>
                                                            <!-- SURNAME IN PAGE TITLE -->
                                                            <td>
                                                                <label class="showname">
                                                                    <?= $this_ITEM['SURNAME'] ?>
                                                                </label>
                                                                <input
                                                                    class="form-control editname"
                                                                    name="surname[<?= $key ?>]"
                                                                    type="text"
                                                                    value="<?= $this_ITEM['SURNAME'] ?>"
                                                                    >
                                                            </td>
                                                        <?php endif ?>
                                                        <!-- PAGE TITLE -->
                                                        <td>
                                                            <a href="module.php?mod=<?= $this->getName(); ?>&amp;mod_action=page&amp;ged=<?= $this->tree()->getNameHtml(); ?>&amp;rootid=<?= $this_ITEM['PID'] ?>" target="_blank">
                                                                <?php
                                                                if ($this->options('use_fullname') == true) {
                                                                    echo I18N::translate('Descendants of %s', Individual::getInstance($this_ITEM['PID'], $this->tree())->getFullName());
                                                                } else {
                                                                    echo I18N::translate('Descendants of the %s family', $this_ITEM['SURNAME']);
                                                                }
                                                                ?>
                                                            </a>
                                                        </td>
                                                        <!-- ACCESS LEVEL -->
                                                        <td>
                                                            <?= FunctionsEdit::editFieldAccessLevel('access_level[' . $key . ']', $this_ITEM['ACCESS_LEVEL'], 'class="form-control"') ?>
                                                        </td>
                                                        <!-- DELETE BUTTON -->
                                                        <td>
                                                            <button	type="button" name="delete" class="btn btn-danger btn-sm" data-key="<?= $key ?>" title="<?php I18N::translate('Delete') ?>">
                                                                <i class="fa fa-trash-o"></i>
                                                            </button>
                                                        </td>
                                                    </tr>
                                                <?php else: ?>
                                                    <tr>
                                                        <!-- SURNAME -->
                                                        <td class="error">
                                                            <input
                                                                name="pid[<?= $key ?>]"
                                                                type="hidden"
                                                                value="<?= $this_ITEM['PID'] ?>"
                                                                >
                                                                <?= $this_ITEM['SURNAME'] ?>
                                                        </td>
                                                        <!-- ERROR MESSAGE -->
                                                        <td colspan="4" class="error">
                                                            <?= I18N::translate('This individual doesn’t exist anymore in this tree') ?>
                                                        </td>
                                                        <!-- DELETE BUTTON -->
                                                        <td>
                                                            <button name="delete" type="button" class="btn btn-danger btn-sm" data-key="<?= $key ?>" title="<?php I18N::translate('Delete') ?>">
                                                                <i class="fa fa-trash-o"></i>
                                                            </button>
                                                        </td>
                                                    </tr>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <!-- BUTTONS -->
                                <button name="update" class="btn btn-primary" type="submit">
                                    <i class="fa fa-check"></i>
                                    <?= I18N::translate('update') ?>
                                </button>
                            </form>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>

        <!-- ACCORDION 2 -->
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                    <?= I18N::translate('Options for %s', $this->tree()->getTitleHtml()) ?>
                </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse show" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <?= $this->addMessage('save-options', 'success', true, I18N::translate('The options for this tree are succesfully saved')) ?>
                    <?= $this->addMessage('reset-options', 'success', true, I18N::translate('The options for this tree are succesfully reset to the default settings')) ?>
                    <?= $this->addMessage('copy-options', 'success', true, I18N::translate('The options for this tree are succesfully saved and copied to all other trees')) ?>
                    <div id="ftv-options-form" class="form-group">
                        <form class="form-horizontal" method="post" name="form5">
                            <!-- USE FULLNAME IN MENU -->
                            <div class="form-group fullname">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Use fullname in menu') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= FunctionsEdit::editFieldYesNo('NEW_FTV_OPTIONS[USE_FULLNAME]', $this->options('use_fullname'), 'class="radio-inline"') ?>
                                </div>
                            </div>
                            <!-- GENERATION BLOCKS -->
                            <div class="form-group">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Number of generation blocks to show') ?>
                                </label>
                                <div class="col-sm-4">
                                    <?= FunctionsEdit::selectEditControl('NEW_FTV_OPTIONS[NUMBLOCKS]', [I18N::translate('All'), '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], null, $this->options('numblocks'), 'class="form-control"') ?>									</div>
                                <p class="col-sm-8 col-sm-offset-4 small text-muted">
                                    <?= /* I18N: Help text for the “Number of generation blocks to show” configuration setting */ I18N::translate('This option is especially usefull for large trees. When you notice a slow page load, here you can set the number of generation blocks to load at once to a lower level. Below the last generation block a button will appear to add the next set of generation blocks. The new blocks will be added to the blocks already loaded. Clicking on a “follow” link in the last visible generation block, will also load the next set of generation blocks.') ?>
                                </p>
                            </div>
                            <!-- SHOW SINGLES -->
                            <div class="form-group">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Show singles') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= FunctionsEdit::editFieldYesNo('NEW_FTV_OPTIONS[SHOW_SINGLES]', $this->options('show_singles'), 'class="radio-inline"') ?>									</div>
                                <p class="col-sm-8 col-sm-offset-4 small text-muted">
                                    <?= /* I18N: Help text for the “Show singles” configuration setting */ I18N::translate('Turn this option on if you want to display singles in the next generation blocks. Singles are individuals without partner and children. With this option turned on, every child of a family will be displayed in a detailed way in the next generation block.') ?>
                                </p>
                            </div>
                            <!-- CHECK RELATIONSHIP -->
                            <div class="form-group">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Check relationship between partners') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= FunctionsEdit::editFieldYesNo('NEW_FTV_OPTIONS[CHECK_RELATIONSHIP]', $this->options('check_relationship'), 'class="radio-inline"') ?>
                                </div>
                                <p class="col-sm-8 col-sm-offset-4 small text-muted">
                                    <?= /* I18N: Help text for the “Check relationship between partners” configuration setting */ I18N::translate('With this option turned on, the script checks if a (married) couple has the same ancestors. If a relationship between the partners is found, a text will appear between brackets after the spouses’ name to indicate the blood relationship.') ?></p>
                                <p class="col-sm-8 col-sm-offset-4 small text-muted">
                                    <?= /* I18N: Warning when using the “Check relationship between partners” configuration setting */ I18N::translate('<strong>Note</strong>: this option can be time and/or memory consuming, especially on large trees. It can cause very slow page loading or an ’execution time out error’ on your server. If you notice such a behavior, reduce the number of generation blocks to load at once or don’t use it in combination with the option to show singles (see the previous options). If you still experience any problems, don’t use this option at all.') ?>
                                </p>
                            </div>
                            <!-- SHOW PLACES -->
                            <div id="places" class="form-group">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Show places') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= FunctionsEdit::editFieldYesNo('NEW_FTV_OPTIONS[SHOW_PLACES]', $this->options('show_places'), 'class="radio-inline"') ?>
                                </div>
                            </div>
                            <!-- USE GEDCOM PLACE SETTING -->
                            <div id="gedcom_places" class="form-group<?php if (!$this->options('show_places')) echo ' collapse' ?>">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Use default GEDCOM settings to abbreviate place names') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= FunctionsEdit::editFieldYesNo('NEW_FTV_OPTIONS[USE_GEDCOM_PLACES]', $this->options('use_gedcom_places'), 'class="radio-inline"') ?>
                                </div>
                                <p class="col-sm-8 col-sm-offset-4 small text-muted">
                                    <?= /* I18N: Help text for the “Use default GEDCOM settings to abbreviate place names” configuration setting */ I18N::translate('If you have ticked the “Show places” option, you can choose to use the default GEDCOM settings to abbreviate placenames. If you don’t set this option, full place names will be shown.') ?>
                                </p>
                            </div>
                            <!-- GET COUNTRYLIST -->
                            <?php if ($this->getCountrylist()): ?>
                                <div id="country_list" class="form-group<?php if (!$this->options('show_places') || $this->options('use_gedcom_places')) echo ' collapse' ?>">
                                    <label class="control-label col-sm-4">
                                        <?= I18N::translate('Select your country') ?>
                                    </label>
                                    <div class="col-sm-8">
                                        <?= FunctionsEdit::selectEditControl('NEW_FTV_OPTIONS[COUNTRY]', $this->getCountryList(), '', $this->options('country'), 'class="form-control"') ?>
                                    </div>
                                    <p class="col-sm-8 col-sm-offset-4 small text-muted">
                                        <?= /* I18N: Help text for the “Select your country” configuration setting */ I18N::translate('If you have ticked the “Show places” option but NOT the option to abbreviate placenames, you can set your own country here. Full places will be listed on the Fancy Treeview pages, but when a place includes the name of your own country, this name will be left out. If you don’t select a country then all countries will be shown, including your own.') ?>
                                    </p>
                                </div>
                            <?php endif; ?>
                            <!-- SHOW OCCUPATIONS -->
                            <div class="form-group">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Show occupations') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= FunctionsEdit::editFieldYesNo('NEW_FTV_OPTIONS[SHOW_OCCU]', $this->options('show_occu'), 'class="radio-inline"') ?>
                                </div>
                            </div>
                            <!-- RESIZE THUMBS -->
                            <div id="resize_thumbs" class="form-group">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Resize thumbnails') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= FunctionsEdit::editFieldYesNo('NEW_FTV_OPTIONS[RESIZE_THUMBS]', $this->options('resize_thumbs'), 'class="radio-inline"') ?>
                                </div>
                                <p class="col-sm-8 col-sm-offset-4 small text-muted">
                                    <?= /* I18N: Help text for the “Resize thumbnails” configuration setting */ I18N::translate('Here you can choose to resize the default webtrees thumbnails especially for the Fancy Treeview pages. You can set a custom size in percentage or in pixels. If you choose “no” the default webtrees thumbnails will be used with the formats you have set on the tree configuration page.') ?>									</p>
                            </div>
                            <!-- THUMB SIZE -->
                            <div id="thumb_size" class="form-group<?php if (!$this->options('resize_thumbs')) echo ' collapse' ?>">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Thumbnail size') ?>
                                </label>
                                <div class="row">
                                    <div class="col-sm-1">
                                        <input
                                            class="form-control"
                                            id="NEW_FTV_OPTIONS[THUMB_SIZE]"
                                            name="NEW_FTV_OPTIONS[THUMB_SIZE]"
                                            type="text"
                                            value="<?= $this->options('thumb_size') ?>"
                                            >
                                    </div>
                                    <div class="col-sm-2">
                                        <?= FunctionsEdit::selectEditControl('NEW_FTV_OPTIONS[THUMB_RESIZE_FORMAT]', ['1' => I18N::translate('percent'), '2' => I18N::translate('pixels')], null, $this->options('thumb_resize_format'), 'class="form-control"') ?>
                                    </div>
                                </div>
                            </div>
                            <!-- SQUARE THUMBS -->
                            <div id="square_thumbs" class="form-group<?php if (!$this->options('resize_thumbs')) echo ' collapse' ?>">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Use square thumbnails') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= FunctionsEdit::editFieldYesNo('NEW_FTV_OPTIONS[USE_SQUARE_THUMBS]', $this->options('use_square_thumbs'), 'class="radio-inline"') ?>
                                </div>
                            </div>
                            <!-- SHOW USERFORM -->
                            <div class="form-group">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Show form to change start person') ?>
                                </label>
                                <div class="col-sm-4">
                                    <?= FunctionsEdit::editFieldAccessLevel('NEW_FTV_OPTIONS[SHOW_USERFORM]', $this->options('show_userform'), 'class="form-control"') ?>
                                </div>
                            </div>
                            <!-- SHOW FANCY TREEVIEW ON INDI PAGE -->
                            <div class="form-group">
                                <label class="control-label col-sm-4">
                                    <?= I18N::translate('Show a Fancy Treeview tab on the individual page') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= FunctionsEdit::editFieldYesNo('NEW_FTV_OPTIONS[FTV_TAB]', $this->options('ftv_tab'), 'class="radio-inline"') ?>
                                </div>
                                <p class="col-sm-8 col-sm-offset-4 small text-muted">
                                    <?= /* I18N: Help text for the “Show Fancy Treeview on Indi Page” configuration setting */ I18N::translate('If you enable this option, a Fancy Treeview tab with the title “Descendants” will be shown on the individual page. The tab will describe the current individual with his family and the next two generations (if there are any). If this individual has more descendants than the two generations shown, a link will be displayed to the full Fancy Treeview Page where this individual will be displayed with all his descendants.') ?>
                                </p>
                            </div>
                            <!-- BUTTONS -->
                            <div class="form-group">
                                <div class="col-md-6">
                                    <button name="save-options" class="btn btn-primary" type="submit">
                                        <i class="fa fa-check"></i>
                                        <?= I18N::translate('save') ?>
                                    </button>
                                    <button name="reset-options" class="btn btn-primary" type="reset">
                                        <i class="fa fa-recycle"></i>
                                        <?= I18N::translate('reset') ?>
                                    </button>
                                </div>
                                <?php if (count(Tree::getAll()) > 1): ?>
                                    <div class="col-md-6 text-right">
                                        <button id="save-and-copy" name="copy-options" class="btn btn-primary" type="button">
                                            <i class="fa fa-check"></i>
                                            <?= I18N::translate('save and copy options to other trees') ?>
                                        </button>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
