<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="d-flex mb-3">
    <h3 class="justify-content-start ms-0 me-auto"><?= $tab_page_title ?></h3>
    <div class="justify-content-end">
        <button class="jc-fancy-treeview-toggle-button btn btn-primary" type="button">
            <?= I18N::translate('Show') . ' ' . strtolower(I18N::translate($tab_button_text)) ?>
        </button>
    </div>
</div>
<ol class="jc-fancy-treeview-page-body"><?= $tab_content ?></ol>
