<?php

use Fisharebest\Webtrees\View;

?>

<div id="jc-fancy-treeview-tab-descendants" class="jc-fancy-treeview-page jc-fancy-treeview-tab py-4 px-1 collapse show">
    <?= View($module->name() . '::tab-content', [
        'tab_button_text'=> 'Ancestors',
        'tab_page_title' => $tab_page_title_descendants,
        'tab_content'    => $tab_content_descendants
    ]) ?>
    <?= View($module->name() . '::readmore-link', ['url' => $module->getUrl($tree, $pid, 'descendants')]); ?>
</div>

<div id="jc-fancy-treeview-tab-ancestors" class="jc-fancy-treeview-page jc-fancy-treeview-tab py-4 px-1 collapse">
    <?= View($module->name() . '::tab-content', [
        'tab_button_text'=> 'Descendants',
        'tab_page_title' => $tab_page_title_ancestors,
        'tab_content'    => $tab_content_ancestors
    ]) ?>
    <?= View($module->name() . '::readmore-link', ['url' => $module->getUrl($tree, $pid, 'ancestors')]); ?>
</div>

<?php View::push('javascript') ?>
<script>
    $('.jc-fancy-treeview-toggle-button').on('click', function() {
        $('#jc-fancy-treeview-tab-ancestors, #jc-fancy-treeview-tab-descendants').toggleClass('show');
    });
</script>
<?php View::endpush() ?>
